title: Tristan John David 
logo: "/profile.jpg?raw=true"
description:
 Computer System Technician CO OP Student
  <br><br>
  <img src="https://upload.wikimedia.org/wikipedia/commons/5/53/Seneca_logo.png" width="20" height="20"><a href="mailto:tjdavid@myseneca.ca">tjdavid@myseneca.ca </a>
  <br>
  <img src="https://upload.wikimedia.org/wikipedia/commons/6/65/Linkedin-png-linkedin-icon-1600.png" width="20" height="20"><a href="https://www.linkedin.com/in/tristandavid20/">LinkedIn Profile</a>
  <br>
  <img src="https://upload.wikimedia.org/wikipedia/commons/c/cf/GitHub-Mark.png" width="20" height="20"><a href="https://tristandavid.github.io/">Github</a>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
theme: jekyll-theme-minimal
