title: Tristan John David 
logo: "/profile.jpg?raw=true"
description:
 Computer System Technician CO OP Student
  <br><br>
  <img src="/email.png?raw=true" width="20" height="20"><a href="mailto:tjdavid@myseneca.ca">tjdavid@myseneca.ca </a>
  <br>
  <img src="/linkedin.png?raw=true" width="20" height="20"><a href="https://www.linkedin.com/in/tristandavid20/">LinkedIn Profile</a>
  <br>
  <img src="/github.png?raw=true" width="20" height="20"><a href="https://tristandavid.github.io/">Github</a>
  <br>
  <img src="/resumelogo.png?raw=true" width="20" height="20"><a href="https://drive.google.com/file/d/1hi-3EzuQ8MWHPji7vbxVUFEUpAutRdEY/view?usp=sharing/">Download a copy of my resume</a>
theme: jekyll-theme-minimal
